const LOCALHOST_API_BASE_URL = 'http://localhost:8000'
const API_ENDPOINT = `${process.env.NEXT_PUBLIC_API_BASE_URL || LOCALHOST_API_BASE_URL}/api`
const ACCOUNTS_ENDPOINT = `${process.env.NEXT_PUBLIC_API_BASE_URL || LOCALHOST_API_BASE_URL}/accounts`

// export
export { API_ENDPOINT, ACCOUNTS_ENDPOINT }
